#!/bin/bash

# Copyright BobbyUnknown 2025 | https://github.com/bobbyunknown

REPO_FILE="../config.txt"
TEMP_DIR="temp_packages"
CHECK_VERSION_DIR="package_version"

git clone --quiet --branch package --single-branch --depth 1 https://github.com/bobbyunknown/insomwrt-package.git "$CHECK_VERSION_DIR"

mkdir -p "$TEMP_DIR"
cd "$TEMP_DIR"

while IFS= read -r repo || [ -n "$repo" ]; do
    [[ $repo =~ ^#.*$ || -z $repo ]] && continue
    
    REPO_NAME=$(echo "$repo" | cut -d'/' -f2)
    
    CURRENT_VERSION=""
    if [ -f "../$CHECK_VERSION_DIR/ipk_version/${REPO_NAME}_version.txt" ]; then
        CURRENT_VERSION=$(cat "../$CHECK_VERSION_DIR/ipk_version/${REPO_NAME}_version.txt")
    fi
    
    LATEST_RELEASE=$(curl -s "https://api.github.com/repos/$repo/releases/latest")
    VERSION=$(echo $LATEST_RELEASE | jq -r '.tag_name')
    
    if [ "$VERSION" != "$CURRENT_VERSION" ]; then
        echo "Memperbarui $REPO_NAME ke versi $VERSION"
        
        echo $LATEST_RELEASE | jq -r '.assets[].browser_download_url' | while read url; do
            wget -q "$url"
        done
        
        mkdir -p "../aarch64_generic"
        mkdir -p "../ipk_version"
        mv *.ipk "../aarch64_generic/"
        echo "$VERSION" > "../ipk_version/${REPO_NAME}_version.txt"
    else
        echo "$REPO_NAME sudah versi terbaru ($VERSION)"
    fi
done < "$REPO_FILE"

cd ..
rm -rf "$TEMP_DIR"
rm -rf "$CHECK_VERSION_DIR"
