# Copyright BobbyUnknown 2025 | https://github.com/bobbyunknown

name: Build OpenWrt Feed

on:
  push:
    branches:
      - package
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Package Index
        run: |
          cd aarch64_generic
          
          # Hapus file index lama jika ada
          rm -f Packages Packages.gz Packages.manifest
          
          for IPK in *.ipk; do
            [ -f "$IPK" ] || continue
            
            tar -xzOf "$IPK" ./control.tar.gz | tar -xzOf - ./control >> Packages
            
            echo "Filename: $IPK" >> Packages
            echo "Size: $(stat -c %s $IPK)" >> Packages
            echo "MD5Sum: $(md5sum $IPK | cut -d' ' -f1)" >> Packages
            echo "SHA256sum: $(sha256sum $IPK | cut -d' ' -f1)" >> Packages
            echo "" >> Packages
          done
          
          # Buat Packages.gz
          gzip -k -f Packages
          
          # Buat Packages.manifest
          cp Packages Packages.manifest

      - name: Commit dan Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update package feeds" || echo "No changes to commit"
          git push 