name: Get ipk

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: main-repo
      
      - uses: actions/checkout@v4
        with:
          ref: package
          path: package-repo
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get package
        working-directory: main-repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            chmod +x scripts/passwall_package
            chmod +x scripts/general_package
            bash scripts/passwall_package
            bash scripts/general_package
        
      - name: Update package branch
        run: |
          mkdir -p package-repo/aarch64_generic
          
          cp -r main-repo/aarch64_generic/* package-repo/aarch64_generic/
          
          cd package-repo
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -f aarch64_generic/
          git commit -m "🤖 Auto Update IPK packages $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin package
