# Copyright BobbyUnknown 2025 | https://github.com/bobbyunknown

name: Get ipk

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: main-repo
      
      - uses: actions/checkout@v4
        with:
          ref: package
          path: package-repo
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get package
        working-directory: main-repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            chmod +x scripts/*
            for script in scripts/*_package; do
              if [ -f "$script" ]; then
                echo "Running $script..."
                bash "$script"
              fi
            done
        
      - name: Update package branch
        run: |
          mkdir -p package-repo/aarch64_generic
          mkdir -p package-repo/ipk_version
          
          cp -r main-repo/aarch64_generic/* package-repo/aarch64_generic/ || true
          cp -r main-repo/ipk_version/* package-repo/ipk_version/ || true
          
          cd package-repo
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -f aarch64_generic/
          git add -f ipk_version/
          git commit -m "🤖 Auto Update IPK packages $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin package
