name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      
      - name: Checkout package branch
        uses: actions/checkout@v4
        with:
          ref: package
          path: package-branch

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build site
        run: |
          mkdir -p _site/aarch64_generic
          cp -r package-branch/aarch64_generic/* _site/aarch64_generic/
          
          PACKAGE_LIST=""
          cd package-branch/aarch64_generic
          for file in *.ipk; do
            if [ -f "$file" ]; then
              name=$(echo "$file" | sed -E 's/_[0-9].*//')
              version=$(echo "$file" | grep -oP '(?<=_)[0-9][^_]*(?=_)' || echo "unknown")
              size=$(ls -lh "$file" | awk '{print $5}')
              PACKAGE_LIST="$PACKAGE_LIST<tr><td>$name</td><td>$version</td><td>$size</td></tr>"
            fi
          done
          cd ../..
          
          cp index.html _site/
          sed -i "s|<!-- PACKAGE_LIST -->|$PACKAGE_LIST|" _site/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4